In [2]:
from theano import *
import theano.tensor as T
import numpy as np

In [3]:
a = np.asarray([[1., 2], [3, 4], [5, 6]])

In [4]:
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [5]:
a.shape

(3, 2)

In [6]:
a.shape()

TypeError: 'tuple' object is not callable

In [7]:
a.shape

(3, 2)

In [8]:
a[2]

array([ 5.,  6.])

In [9]:
a[2, 0]

5.0

## Broadcasting

In [10]:
a = np.asarray([1.0, 2.0, 3.0])

In [11]:
b = 2.0

In [12]:
a * b

array([ 2.,  4.,  6.])